language: node_js
sudo: required
branches:
  only:
    - master
services:
- docker
matrix:
  include:
    - node_js: '10'
      env: NODE_VERSION=10
    - node_js: '12'
      env: NODE_VERSION=12
before_install:
- npm install -g npm@'>=2.13.5'
- npm run start-docker
- npm run waitfor-docker
install:
- npm i
script: npm test
after_script:
- npm run stop-docker
