language: node_js
sudo: required
branches:
  only:
    - master
services:
  - docker
matrix:
  include:
    - node_js: '10'
      env: NODE_VERSION=10
    - node_js: '12'
      env: NODE_VERSION=12
    - node_js: '14'
      env: NODE_VERSION=14
    - node_js: '16'
      env: NODE_VERSION=16
before_install:
  - npm install -g npm@'>=2.13.5'
  - npm run start-docker
  - npm run waitfor-docker
  - echo "//npm.pkg.github.com/:_authToken=\${NPM_TOKEN}" > .npmrc
install:
  - npm i
script: npm test
after_script:
  - npm run stop-docker
